### ISSUE TITLE
question: both gzip and brotli?

### ISSUE THREAD

**Issue by jamesdixon** [marcotc/rack-brotli#4]
Hi, 

I saw [an article](https://pawelurbanek.com/rails-gzip-brotli-compression) that seemed to indicate that both Rack::Deflater and Rack::Brotli could be used simultaneously with one taking precedence? Can you confirm?

Thank you!

**Comment by marcotc** [comment]
Hey @jamesdixon, that is correct.

Both [Rack::Deflate](https://github.com/rack/rack/blob/1f5763de6a9fe515ff84992b343d63c88104654c/lib/rack/deflater.rb#L127) and [Rack::Brotli](https://github.com/marcotc/rack-brotli/blob/2d25bdf798e185f624435cc03059f5ca74802e3f/lib/rack/brotli/deflater.rb#L97) middleware check if the response is not already encoded before compressing it, so they are safe to use together.

One thing to keep in mind, that is also mentioned in @pawurb's article, is that the order you mount them is important. Rack calls all middleware in the order they are mounted: this means that for HTTP requests, first mounted is first processed, but for HTTP responses, *last* mounted is first processed. Because we are compressing the HTTP response, we would like to be mounted last instead of first:

```ruby
use Rack::Deflater
use Rack::Brotli
```

Because pretty much all browsers support both `gzip` and `br`, whichever middleware processes the response first will get to encode it.

**Comment by jamesdixon** [comment]
@marcotc thank you for the detailed information! Appreciated 🙏
